# Generated by Django 4.1.7 on 2023-03-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_selecting_fields_field10_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecting_fields',
            old_name='field1_active',
            new_name='field100_active',
        ),
    ]
