# Generated by Django 4.1.7 on 2023-03-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_logo_delete_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='IMG/'),
        ),
    ]
