# Generated by Django 4.1.7 on 2023-03-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_alter_logo_logo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings_lightnames',
        ),
    ]
